[package]
name = "gr-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gr-core = { path = "../gr-core" }
gr-equity = { path = "../gr-equity" }
gr-parser-api = { path = "../gr-parser-api" }
gr-stats = { path = "../gr-stats" }
r2d2 = "0.8"
r2d2_sqlite = "0.24"
rusqlite = { version = "0.31", features = ["bundled"] }
thiserror = "1"
windows-sys = { version = "0.59", features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
  "Win32_System_WindowsProgramming",
] }
zstd = "0.13"

[dev-dependencies]
gr-parser-winamax = { path = "../gr-parser-winamax" }
tempfile = "3"
